// This test code was generated by Claude (Anthropic).

#ifdef KERNEL_TESTS

#include <containers/kshared_ptr.hpp>
#include <log/log.hpp>
#include <test/test.hpp>

#include <utility>

namespace test_kshared_ptr {

// Tracks construction/destruction so ownership/refcount semantics can be verified.
struct tracked {
    static int alive_count;
    int value;

    explicit tracked(int v)
        : value{v}
    {
        alive_count++;
    }

    ~tracked()
    {
        alive_count--;
    }
};

int tracked::alive_count = 0;

void test_default_constructor()
{
    kshared_ptr<int> p;
    test::assert_null(p.get(), "default constructed kshared_ptr is null");
    test::assert_true(!static_cast<bool>(p), "default constructed kshared_ptr is falsy");
}

void test_make_kshared()
{
    auto p = make_kshared<int>(42);
    test::assert_not_null(p.get(), "make_kshared produces a non-null kshared_ptr");
    test::assert_eq(*p, 42, "make_kshared stores the correct value");
    test::assert_true(static_cast<bool>(p), "make_kshared result is truthy");
}

void test_operator_arrow()
{
    auto p = make_kshared<tracked>(7);
    test::assert_eq(p->value, 7, "operator-> reads member correctly");
    p->value = 100;
    test::assert_eq(p->value, 100, "operator-> allows mutation");
}

void test_destructor_releases_object()
{
    tracked::alive_count = 0;
    {
        auto p = make_kshared<tracked>(1);
        test::assert_eq(tracked::alive_count, 1, "make_kshared constructs the object");
    }
    test::assert_eq(tracked::alive_count, 0, "destroying the last kshared_ptr destroys the object");
}

void test_copy_constructor_shares_ownership()
{
    tracked::alive_count = 0;
    auto p1 = make_kshared<tracked>(5);
    auto p2 = p1;

    test::assert_eq(p1.get(), p2.get(), "copy constructor shares the same underlying object");
    test::assert_eq(tracked::alive_count, 1, "copy constructor does not construct a new object");

    p2->value = 50;
    test::assert_eq(p1->value, 50, "mutation through one copy is visible through the other");
}

void test_copy_constructor_keeps_object_alive()
{
    tracked::alive_count = 0;
    auto p1 = make_kshared<tracked>(1);
    {
        auto p2 = p1;
        test::assert_eq(tracked::alive_count, 1, "object is still alive while a copy exists");
    }
    test::assert_eq(tracked::alive_count, 1, "object survives after only one of two owners is destroyed");
}

void test_destroyed_after_all_copies_released()
{
    tracked::alive_count = 0;
    auto p1 = make_kshared<tracked>(1);
    auto p2 = p1;

    p1 = kshared_ptr<tracked>();
    test::assert_eq(tracked::alive_count, 1, "object survives while the other owner is still alive");

    p2 = kshared_ptr<tracked>();
    test::assert_eq(tracked::alive_count, 0, "object is destroyed once the last owner releases it");
}

void test_move_constructor()
{
    tracked::alive_count = 0;
    auto p1 = make_kshared<tracked>(5);
    kshared_ptr<tracked> p2(std::move(p1));

    test::assert_null(p1.get(), "move constructor empties source");
    test::assert_not_null(p2.get(), "move constructor gives destination ownership");
    test::assert_eq(p2->value, 5, "move constructor preserves value");
    test::assert_eq(tracked::alive_count, 1, "move constructor does not construct/destruct the object");
}

void test_copy_assignment_shares_ownership()
{
    tracked::alive_count = 0;
    auto p1 = make_kshared<tracked>(3);
    kshared_ptr<tracked> p2;

    p2 = p1;

    test::assert_eq(p1.get(), p2.get(), "copy assignment shares the same underlying object");
    test::assert_eq(tracked::alive_count, 1, "copy assignment does not construct a new object");

    p1 = kshared_ptr<tracked>();
    test::assert_eq(tracked::alive_count, 1, "object survives once one of two owners releases it");

    p2 = kshared_ptr<tracked>();
    test::assert_eq(tracked::alive_count, 0, "object is destroyed once the last owner releases it");
}

void test_move_assignment()
{
    tracked::alive_count = 0;
    auto p1 = make_kshared<tracked>(1);
    auto p2 = make_kshared<tracked>(2);

    p2 = std::move(p1);

    test::assert_null(p1.get(), "move assignment empties source");
    test::assert_eq(p2->value, 1, "move assignment transfers source value");
    test::assert_eq(tracked::alive_count, 1, "move assignment destroys the previously held object");
}

void test_move_assignment_to_empty()
{
    tracked::alive_count = 0;
    auto p1 = make_kshared<tracked>(9);
    kshared_ptr<tracked> p2;

    p2 = std::move(p1);

    test::assert_eq(p2->value, 9, "move assignment into empty kshared_ptr transfers value");
    test::assert_eq(tracked::alive_count, 1, "move assignment into empty kshared_ptr keeps single object alive");
}

void run()
{
    log::info("Running kshared_ptr tests...");

    test_default_constructor();
    test_make_kshared();
    test_operator_arrow();
    test_destructor_releases_object();
    test_copy_constructor_shares_ownership();
    test_copy_constructor_keeps_object_alive();
    test_destroyed_after_all_copies_released();
    test_move_constructor();
    test_copy_assignment_shares_ownership();
    test_move_assignment();
    test_move_assignment_to_empty();
}
}

#endif // KERNEL_TESTS
