// This test code was generated by Claude (Anthropic).

#ifdef KERNEL_TESTS

#include <containers/kunique_ptr.hpp>
#include <containers/kvector.hpp>
#include <log/log.hpp>
#include <test/test.hpp>

#include <utility>

namespace test_kunique_ptr {

// Tracks construction/destruction so move/reset semantics can be verified.
struct tracked {
    static int alive_count;
    int value;

    explicit tracked(int v)
        : value{v}
    {
        alive_count++;
    }

    ~tracked()
    {
        alive_count--;
    }
};

int tracked::alive_count = 0;

void test_default_constructor()
{
    kunique_ptr<int> p;
    test::assert_null(p.get(), "default constructed kunique_ptr is null");
    test::assert_true(!static_cast<bool>(p), "default constructed kunique_ptr is falsy");
}

void test_construct_with_args()
{
    kunique_ptr<int> p(42);
    test::assert_not_null(p.get(), "constructed kunique_ptr is non-null");
    test::assert_eq(*p, 42, "constructed kunique_ptr holds correct value");
    test::assert_true(static_cast<bool>(p), "constructed kunique_ptr is truthy");
}

void test_operator_arrow()
{
    kunique_ptr<tracked> p(7);
    test::assert_eq(p->value, 7, "operator-> reads member correctly");
    p->value = 100;
    test::assert_eq(p->value, 100, "operator-> allows mutation");
}

void test_destructor_releases_object()
{
    tracked::alive_count = 0;
    {
        kunique_ptr<tracked> p(1);
        test::assert_eq(tracked::alive_count, 1, "constructing kunique_ptr constructs the object");
    }
    test::assert_eq(tracked::alive_count, 0, "destroying kunique_ptr destroys the object");
}

void test_reset()
{
    tracked::alive_count = 0;
    kunique_ptr<tracked> p(1);
    p.reset();
    test::assert_null(p.get(), "reset() nulls out the pointer");
    test::assert_eq(tracked::alive_count, 0, "reset() destroys the managed object");

    p.reset(); // Should not crash
    test::assert_null(p.get(), "reset() on empty kunique_ptr is safe");
}

void test_move_constructor()
{
    tracked::alive_count = 0;
    kunique_ptr<tracked> p1(5);
    kunique_ptr<tracked> p2(std::move(p1));

    test::assert_null(p1.get(), "move constructor empties source");
    test::assert_not_null(p2.get(), "move constructor gives destination ownership");
    test::assert_eq(p2->value, 5, "move constructor preserves value");
    test::assert_eq(tracked::alive_count, 1, "move constructor does not construct/destruct the object");
}

void test_move_assignment()
{
    tracked::alive_count = 0;
    kunique_ptr<tracked> p1(1);
    kunique_ptr<tracked> p2(2);

    p2 = std::move(p1);

    test::assert_null(p1.get(), "move assignment empties source");
    test::assert_eq(p2->value, 1, "move assignment transfers source value");
    test::assert_eq(tracked::alive_count, 1, "move assignment destroys the previously held object");
}

void test_move_assignment_to_empty()
{
    tracked::alive_count = 0;
    kunique_ptr<tracked> p1(9);
    kunique_ptr<tracked> p2;

    p2 = std::move(p1);

    test::assert_eq(p2->value, 9, "move assignment into empty kunique_ptr transfers value");
    test::assert_eq(tracked::alive_count, 1, "move assignment into empty kunique_ptr keeps single object alive");
}

// ==========================================================================
// kunique_ptr<kvector<T>> - complex/non-trivial managed type
// ==========================================================================

void test_kvector_default_construct()
{
    // Zero args resolves to kunique_ptr's own default constructor (empty/no
    // managed object), not an allocated empty kvector - matches unique_ptr
    // semantics where the default state means "owns nothing".
    kunique_ptr<kvector<int>> p;
    test::assert_null(p.get(), "kunique_ptr<kvector<int>> default constructor owns nothing");
}

void test_kvector_initializer_list_forwarding()
{
    // A bare {1, 2, 3} can't be deduced through the variadic Args&&... pack
    // (same limitation std::make_unique has), so the initializer_list must
    // be spelled out explicitly here.
    kunique_ptr<kvector<int>> p(std::initializer_list<int>{1, 2, 3});
    test::assert_eq(p->size(), 3ul, "kunique_ptr<kvector<int>> forwards initializer_list constructor");
    test::assert_eq((*p)[0], 1, "kunique_ptr<kvector<int>> initializer_list element 0");
    test::assert_eq((*p)[2], 3, "kunique_ptr<kvector<int>> initializer_list element 2");
}

void test_kvector_count_constructor_forwarding()
{
    // Regression test: the variadic constructor must use parens (new T(args...))
    // rather than braces, otherwise brace-init would prefer kvector's
    // initializer_list constructor over the (count, value) constructor here.
    kunique_ptr<kvector<int>> p(5, 42);
    test::assert_eq(p->size(), 5ul, "kunique_ptr<kvector<int>> forwards (count, value) constructor");
    test::assert_eq((*p)[0], 42, "kunique_ptr<kvector<int>> (count, value) element 0");
    test::assert_eq((*p)[4], 42, "kunique_ptr<kvector<int>> (count, value) element 4");
}

void test_kvector_mutate_through_pointer()
{
    kunique_ptr<kvector<int>> p(std::initializer_list<int>{1, 2, 3});
    p->push_back(4);
    test::assert_eq(p->size(), 4ul, "push_back through operator-> grows managed kvector");
    test::assert_eq((*p)[3], 4, "push_back through operator-> stores new element");
}

void test_kvector_of_trackable_elements()
{
    tracked::alive_count = 0;
    {
        kunique_ptr<kvector<tracked>> p;
        kvector<tracked> v;
        v.emplace_back(1);
        v.emplace_back(2);
        v.emplace_back(3);
        test::assert_eq(tracked::alive_count, 3, "constructing elements increments alive_count");

        p = kunique_ptr<kvector<tracked>>(std::move(v));
        test::assert_eq(tracked::alive_count, 3, "moving kvector into kunique_ptr preserves elements");
        test::assert_eq(p->size(), 3ul, "kunique_ptr<kvector<tracked>> has 3 elements");
    }
    test::assert_eq(tracked::alive_count, 0, "destroying kunique_ptr<kvector<tracked>> destroys all elements");
}

void test_nested_kunique_ptr()
{
    kunique_ptr<kunique_ptr<int>> outer(kunique_ptr<int>(99));
    test::assert_not_null(outer.get(), "kunique_ptr<kunique_ptr<int>> outer is non-null");
    test::assert_not_null((*outer).get(), "kunique_ptr<kunique_ptr<int>> inner is non-null");
    test::assert_eq(**outer, 99, "kunique_ptr<kunique_ptr<int>> dereferences through both layers");
}

void run()
{
    log::info("Running kunique_ptr tests...");

    test_default_constructor();
    test_construct_with_args();
    test_operator_arrow();
    test_destructor_releases_object();
    test_reset();
    test_move_constructor();
    test_move_assignment();
    test_move_assignment_to_empty();

    // kunique_ptr<kvector<T>> tests
    test_kvector_default_construct();
    test_kvector_initializer_list_forwarding();
    test_kvector_count_constructor_forwarding();
    test_kvector_mutate_through_pointer();
    test_kvector_of_trackable_elements();

    // Nested kunique_ptr
    test_nested_kunique_ptr();
}
}

#endif // KERNEL_TESTS
