// This test code was generated by Claude (Anthropic).

#ifdef KERNEL_TESTS

#include <exclusive/katomic.hpp>
#include <log/log.hpp>
#include <test/test.hpp>

namespace test_katomic {

void test_default_constructor()
{
    katomic<int> a;
    test::assert_eq(a.load(), 0, "default constructed katomic is zero");
}

void test_value_constructor()
{
    katomic<int> a(42);
    test::assert_eq(a.load(), 42, "value constructed katomic holds correct value");
}

void test_store()
{
    katomic<int> a(1);
    a.store(99);
    test::assert_eq(a.load(), 99, "store() updates the value");
}

void test_exchange()
{
    katomic<int> a(5);
    int previous = a.exchange(10);
    test::assert_eq(previous, 5, "exchange() returns the previous value");
    test::assert_eq(a.load(), 10, "exchange() stores the new value");
}

void test_pre_increment()
{
    katomic<int> a(5);
    int result = ++a;
    test::assert_eq(result, 6, "pre-increment returns updated value");
    test::assert_eq(a.load(), 6, "pre-increment updates stored value");
}

void test_pre_decrement()
{
    katomic<int> a(5);
    int result = --a;
    test::assert_eq(result, 4, "pre-decrement returns updated value");
    test::assert_eq(a.load(), 4, "pre-decrement updates stored value");
}

void test_post_increment()
{
    katomic<int> a(5);
    int result = a++;
    test::assert_eq(result, 5, "post-increment returns previous value");
    test::assert_eq(a.load(), 6, "post-increment updates stored value");
}

void test_post_decrement()
{
    katomic<int> a(5);
    int result = a--;
    test::assert_eq(result, 5, "post-decrement returns previous value");
    test::assert_eq(a.load(), 4, "post-decrement updates stored value");
}

void test_add_assign()
{
    katomic<int> a(10);
    int result = a += 5;
    test::assert_eq(result, 15, "+= returns updated value");
    test::assert_eq(a.load(), 15, "+= updates stored value");
}

void test_sub_assign()
{
    katomic<int> a(10);
    int result = a -= 4;
    test::assert_eq(result, 6, "-= returns updated value");
    test::assert_eq(a.load(), 6, "-= updates stored value");
}

void test_negative_values()
{
    katomic<int> a(0);
    --a;
    test::assert_eq(a.load(), -1, "katomic correctly stores negative values");
}

void test_equality_operators()
{
    katomic<int> a(7);
    katomic<int> b(7);
    katomic<int> c(8);

    test::assert_true(a == b, "katomics with equal values compare equal");
    test::assert_true(a != c, "katomics with different values compare unequal");
}

void test_relational_operators()
{
    katomic<int> a(3);
    katomic<int> b(8);

    test::assert_true(a < b, "operator< compares loaded values");
    test::assert_true(b > a, "operator> compares loaded values");
    test::assert_true(!(a > b), "operator> is false when lhs is smaller");
}

void test_implicit_conversion()
{
    katomic<int> a(123);
    int value = a;
    test::assert_eq(value, 123, "implicit conversion to T returns loaded value");
}

void run()
{
    log::info("Running katomic tests...");

    test_default_constructor();
    test_value_constructor();
    test_store();
    test_exchange();
    test_pre_increment();
    test_pre_decrement();
    test_post_increment();
    test_post_decrement();
    test_add_assign();
    test_sub_assign();
    test_negative_values();
    test_equality_operators();
    test_relational_operators();
    test_implicit_conversion();
}
}

#endif // KERNEL_TESTS
